// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: relaymesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerAdvertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerAdvertisement) Reset() {
	*x = PeerAdvertisement{}
	mi := &file_relaymesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAdvertisement) ProtoMessage() {}

func (x *PeerAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAdvertisement.ProtoReflect.Descriptor instead.
func (*PeerAdvertisement) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{0}
}

func (x *PeerAdvertisement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerAdvertisement) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerAdvertisement) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerAdvertisement) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerAdvertisement) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RelayPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       uint32                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	PacketId      string                 `protobuf:"bytes,8,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	HopCount      uint32                 `protobuf:"varint,9,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Path          []string               `protobuf:"bytes,10,rep,name=path,proto3" json:"path,omitempty"`
	Priority      uint32                 `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayPacket) Reset() {
	*x = RelayPacket{}
	mi := &file_relaymesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayPacket) ProtoMessage() {}

func (x *RelayPacket) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayPacket.ProtoReflect.Descriptor instead.
func (*RelayPacket) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{1}
}

func (x *RelayPacket) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RelayPacket) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RelayPacket) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RelayPacket) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *RelayPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RelayPacket) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RelayPacket) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *RelayPacket) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *RelayPacket) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RelayPacket) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RoutingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Routes        []*NodeRouteEntry      `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingUpdate) Reset() {
	*x = RoutingUpdate{}
	mi := &file_relaymesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingUpdate) ProtoMessage() {}

func (x *RoutingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingUpdate.ProtoReflect.Descriptor instead.
func (*RoutingUpdate) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{2}
}

func (x *RoutingUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RoutingUpdate) GetRoutes() []*NodeRouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RoutingUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NodeRouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Expiry        int64                  `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRouteEntry) Reset() {
	*x = NodeRouteEntry{}
	mi := &file_relaymesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRouteEntry) ProtoMessage() {}

func (x *NodeRouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRouteEntry.ProtoReflect.Descriptor instead.
func (*NodeRouteEntry) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{3}
}

func (x *NodeRouteEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *NodeRouteEntry) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *NodeRouteEntry) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *NodeRouteEntry) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerAdvertisement   `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_relaymesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{4}
}

func (x *PeerList) GetPeers() []*PeerAdvertisement {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerList) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_relaymesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ack) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	MaxHops       uint32                 `protobuf:"varint,3,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_relaymesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{6}
}

func (x *RouteRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RouteRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteRequest) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *RouteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_relaymesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{7}
}

func (x *RouteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RouteResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RouteResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RouteResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Routes        []*RouteTableEntry     `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
	mi := &file_relaymesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTable.ProtoReflect.Descriptor instead.
func (*RouteTable) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{8}
}

func (x *RouteTable) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteTable) GetRoutes() []*RouteTableEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteTable) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteTableEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	NextHop       string                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	HopCount      uint32                 `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Expiry        int64                  `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableEntry) Reset() {
	*x = RouteTableEntry{}
	mi := &file_relaymesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableEntry) ProtoMessage() {}

func (x *RouteTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableEntry.ProtoReflect.Descriptor instead.
func (*RouteTableEntry) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{9}
}

func (x *RouteTableEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteTableEntry) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *RouteTableEntry) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RouteTableEntry) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *RouteTableEntry) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type RouteInvalidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInvalidation) Reset() {
	*x = RouteInvalidation{}
	mi := &file_relaymesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInvalidation) ProtoMessage() {}

func (x *RouteInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInvalidation.ProtoReflect.Descriptor instead.
func (*RouteInvalidation) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{10}
}

func (x *RouteInvalidation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RouteInvalidation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteInvalidation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RouteInvalidation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type EgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TargetHost    string                 `protobuf:"bytes,2,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRequest) Reset() {
	*x = EgressRequest{}
	mi := &file_relaymesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRequest) ProtoMessage() {}

func (x *EgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRequest.ProtoReflect.Descriptor instead.
func (*EgressRequest) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{11}
}

func (x *EgressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EgressRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *EgressRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *EgressRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EgressRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type EgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressResponse) Reset() {
	*x = EgressResponse{}
	mi := &file_relaymesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressResponse) ProtoMessage() {}

func (x *EgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressResponse.ProtoReflect.Descriptor instead.
func (*EgressResponse) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{12}
}

func (x *EgressResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EgressResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EgressResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EgressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latency       float64                `protobuf:"fixed64,1,opt,name=latency,proto3" json:"latency,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,2,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,3,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Jitter        float64                `protobuf:"fixed64,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Congestion    float64                `protobuf:"fixed64,5,opt,name=congestion,proto3" json:"congestion,omitempty"`
	HopCount      uint32                 `protobuf:"varint,6,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Stability     float64                `protobuf:"fixed64,7,opt,name=stability,proto3" json:"stability,omitempty"`
	QueueSize     uint64                 `protobuf:"varint,8,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,10,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_relaymesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkMetrics) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *NetworkMetrics) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *NetworkMetrics) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *NetworkMetrics) GetJitter() float64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *NetworkMetrics) GetCongestion() float64 {
	if x != nil {
		return x.Congestion
	}
	return 0
}

func (x *NetworkMetrics) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *NetworkMetrics) GetStability() float64 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *NetworkMetrics) GetQueueSize() uint64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *NetworkMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NetworkMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type PeerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Latency       float64                `protobuf:"fixed64,2,opt,name=latency,proto3" json:"latency,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,3,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMetrics) Reset() {
	*x = PeerMetrics{}
	mi := &file_relaymesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMetrics) ProtoMessage() {}

func (x *PeerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMetrics.ProtoReflect.Descriptor instead.
func (*PeerMetrics) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{14}
}

func (x *PeerMetrics) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerMetrics) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *PeerMetrics) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *PeerMetrics) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *PeerMetrics) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type TelemetryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metrics       *NetworkMetrics        `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	PeerMetrics   []*PeerMetrics         `protobuf:"bytes,3,rep,name=peer_metrics,json=peerMetrics,proto3" json:"peer_metrics,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_relaymesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{15}
}

func (x *TelemetryReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryReport) GetMetrics() *NetworkMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TelemetryReport) GetPeerMetrics() []*PeerMetrics {
	if x != nil {
		return x.PeerMetrics
	}
	return nil
}

func (x *TelemetryReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NetworkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FeatureVector []float32              `protobuf:"fixed32,2,rep,packed,name=feature_vector,json=featureVector,proto3" json:"feature_vector,omitempty"`
	Peers         []*PeerState           `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkState) Reset() {
	*x = NetworkState{}
	mi := &file_relaymesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkState) ProtoMessage() {}

func (x *NetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkState.ProtoReflect.Descriptor instead.
func (*NetworkState) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NetworkState) GetFeatureVector() []float32 {
	if x != nil {
		return x.FeatureVector
	}
	return nil
}

func (x *NetworkState) GetPeers() []*PeerState {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NetworkState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PeerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Latency       float32                `protobuf:"fixed32,2,opt,name=latency,proto3" json:"latency,omitempty"`
	PacketLoss    float32                `protobuf:"fixed32,3,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Bandwidth     float32                `protobuf:"fixed32,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerState) Reset() {
	*x = PeerState{}
	mi := &file_relaymesh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerState) ProtoMessage() {}

func (x *PeerState) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerState.ProtoReflect.Descriptor instead.
func (*PeerState) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{17}
}

func (x *PeerState) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerState) GetLatency() float32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *PeerState) GetPacketLoss() float32 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *PeerState) GetBandwidth() float32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *PeerState) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type RouteRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Path          []string               `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRecommendation) Reset() {
	*x = RouteRecommendation{}
	mi := &file_relaymesh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRecommendation) ProtoMessage() {}

func (x *RouteRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRecommendation.ProtoReflect.Descriptor instead.
func (*RouteRecommendation) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{18}
}

func (x *RouteRecommendation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RouteRecommendation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteRecommendation) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RouteRecommendation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RouteRecommendation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RouteRecommendation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type InferenceRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	State                 *NetworkState          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CandidateDestinations []string               `protobuf:"bytes,2,rep,name=candidate_destinations,json=candidateDestinations,proto3" json:"candidate_destinations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_relaymesh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{19}
}

func (x *InferenceRequest) GetState() *NetworkState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InferenceRequest) GetCandidateDestinations() []string {
	if x != nil {
		return x.CandidateDestinations
	}
	return nil
}

type InferenceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RouteRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	InferenceTimeMs int64                  `protobuf:"varint,2,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_relaymesh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{20}
}

func (x *InferenceResponse) GetRecommendations() []*RouteRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *InferenceResponse) GetInferenceTimeMs() int64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

type TrainingFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Reward        float64                `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingFeedback) Reset() {
	*x = TrainingFeedback{}
	mi := &file_relaymesh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingFeedback) ProtoMessage() {}

func (x *TrainingFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingFeedback.ProtoReflect.Descriptor instead.
func (*TrainingFeedback) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{21}
}

func (x *TrainingFeedback) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *TrainingFeedback) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *TrainingFeedback) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainingFeedback) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_relaymesh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{22}
}

func (x *ModelInfoRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	LastTrained   int64                  `protobuf:"varint,3,opt,name=last_trained,json=lastTrained,proto3" json:"last_trained,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	IsLoaded      bool                   `protobuf:"varint,5,opt,name=is_loaded,json=isLoaded,proto3" json:"is_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_relaymesh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relaymesh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_relaymesh_proto_rawDescGZIP(), []int{23}
}

func (x *ModelInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfo) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ModelInfo) GetLastTrained() int64 {
	if x != nil {
		return x.LastTrained
	}
	return 0
}

func (x *ModelInfo) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ModelInfo) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

var File_relaymesh_proto protoreflect.FileDescriptor

const file_relaymesh_proto_rawDesc = "" +
	"\n" +
	"\x0frelaymesh.proto\x12\trelaymesh\"\x9c\x01\n" +
	"\x11PeerAdvertisement\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xb1\x02\n" +
	"\vRelayPacket\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\a \x01(\rR\aversion\x12\x1b\n" +
	"\tpacket_id\x18\b \x01(\tR\bpacketId\x12\x1b\n" +
	"\thop_count\x18\t \x01(\rR\bhopCount\x12\x12\n" +
	"\x04path\x18\n" +
	" \x03(\tR\x04path\x12\x1a\n" +
	"\bpriority\x18\v \x01(\rR\bpriority\"x\n" +
	"\rRoutingUpdate\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x121\n" +
	"\x06routes\x18\x02 \x03(\v2\x19.relaymesh.NodeRouteEntryR\x06routes\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"r\n" +
	"\x0eNodeRouteEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\x03R\x06expiry\"\\\n" +
	"\bPeerList\x122\n" +
	"\x05peers\x18\x01 \x03(\v2\x1c.relaymesh.PeerAdvertisementR\x05peers\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"W\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x81\x01\n" +
	"\fRouteRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x19\n" +
	"\bmax_hops\x18\x03 \x01(\rR\amaxHops\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"k\n" +
	"\rRouteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"w\n" +
	"\n" +
	"RouteTable\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\x06routes\x18\x02 \x03(\v2\x1a.relaymesh.RouteTableEntryR\x06routes\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x97\x01\n" +
	"\x0fRouteTableEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\rR\bhopCount\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\x03R\x06expiry\"\x83\x01\n" +
	"\x11RouteInvalidation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa3\x01\n" +
	"\rEgressRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vtarget_host\x18\x02 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\rR\n" +
	"targetPort\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\"i\n" +
	"\x0eEgressResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xbb\x02\n" +
	"\x0eNetworkMetrics\x12\x18\n" +
	"\alatency\x18\x01 \x01(\x01R\alatency\x12\x1f\n" +
	"\vpacket_loss\x18\x02 \x01(\x01R\n" +
	"packetLoss\x12\x1c\n" +
	"\tbandwidth\x18\x03 \x01(\x01R\tbandwidth\x12\x16\n" +
	"\x06jitter\x18\x04 \x01(\x01R\x06jitter\x12\x1e\n" +
	"\n" +
	"congestion\x18\x05 \x01(\x01R\n" +
	"congestion\x12\x1b\n" +
	"\thop_count\x18\x06 \x01(\rR\bhopCount\x12\x1c\n" +
	"\tstability\x18\a \x01(\x01R\tstability\x12\x1d\n" +
	"\n" +
	"queue_size\x18\b \x01(\x04R\tqueueSize\x12\x1b\n" +
	"\tcpu_usage\x18\t \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\n" +
	" \x01(\x01R\vmemoryUsage\"\x9c\x01\n" +
	"\vPeerMetrics\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x01R\alatency\x12\x1f\n" +
	"\vpacket_loss\x18\x03 \x01(\x01R\n" +
	"packetLoss\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x01R\tbandwidth\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\"\xb8\x01\n" +
	"\x0fTelemetryReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\ametrics\x18\x02 \x01(\v2\x19.relaymesh.NetworkMetricsR\ametrics\x129\n" +
	"\fpeer_metrics\x18\x03 \x03(\v2\x16.relaymesh.PeerMetricsR\vpeerMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x98\x01\n" +
	"\fNetworkState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0efeature_vector\x18\x02 \x03(\x02R\rfeatureVector\x12*\n" +
	"\x05peers\x18\x03 \x03(\v2\x14.relaymesh.PeerStateR\x05peers\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\tPeerState\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x02R\alatency\x12\x1f\n" +
	"\vpacket_loss\x18\x03 \x01(\x02R\n" +
	"packetLoss\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x02R\tbandwidth\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\"\xb7\x01\n" +
	"\x13RouteRecommendation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04path\x18\x03 \x03(\tR\x04path\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"x\n" +
	"\x10InferenceRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.relaymesh.NetworkStateR\x05state\x125\n" +
	"\x16candidate_destinations\x18\x02 \x03(\tR\x15candidateDestinations\"\x89\x01\n" +
	"\x11InferenceResponse\x12H\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1e.relaymesh.RouteRecommendationR\x0frecommendations\x12*\n" +
	"\x11inference_time_ms\x18\x02 \x01(\x03R\x0finferenceTimeMs\"}\n" +
	"\x10TrainingFeedback\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x01R\x06reward\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"+\n" +
	"\x10ModelInfoRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xab\x01\n" +
	"\tModelInfo\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12!\n" +
	"\flast_trained\x18\x03 \x01(\x03R\vlastTrained\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12\x1b\n" +
	"\tis_loaded\x18\x05 \x01(\bR\bisLoaded2\xd9\x01\n" +
	"\x0eRoutingService\x12=\n" +
	"\bGetRoute\x12\x17.relaymesh.RouteRequest\x1a\x18.relaymesh.RouteResponse\x12?\n" +
	"\rGetRouteTable\x12\x17.relaymesh.RouteRequest\x1a\x15.relaymesh.RouteTable\x12G\n" +
	"\vUpdateRoute\x12\x1a.relaymesh.RouteTableEntry\x1a\x1c.relaymesh.RouteInvalidation2\xdd\x01\n" +
	"\tAIService\x12N\n" +
	"\x11GetRecommendation\x12\x1b.relaymesh.InferenceRequest\x1a\x1c.relaymesh.InferenceResponse\x12=\n" +
	"\x0eReportFeedback\x12\x1b.relaymesh.TrainingFeedback\x1a\x0e.relaymesh.Ack\x12A\n" +
	"\fGetModelInfo\x12\x1b.relaymesh.ModelInfoRequest\x1a\x14.relaymesh.ModelInfo2\x96\x01\n" +
	"\x10TelemetryService\x12=\n" +
	"\x0fReportTelemetry\x12\x1a.relaymesh.TelemetryReport\x1a\x0e.relaymesh.Ack\x12C\n" +
	"\fGetTelemetry\x12\x17.relaymesh.RouteRequest\x1a\x1a.relaymesh.TelemetryReportB*Z(github.com/relaymesh/relaymesh/api/protob\x06proto3"

var (
	file_relaymesh_proto_rawDescOnce sync.Once
	file_relaymesh_proto_rawDescData []byte
)

func file_relaymesh_proto_rawDescGZIP() []byte {
	file_relaymesh_proto_rawDescOnce.Do(func() {
		file_relaymesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relaymesh_proto_rawDesc), len(file_relaymesh_proto_rawDesc)))
	})
	return file_relaymesh_proto_rawDescData
}

var file_relaymesh_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_relaymesh_proto_goTypes = []any{
	(*PeerAdvertisement)(nil),   // 0: relaymesh.PeerAdvertisement
	(*RelayPacket)(nil),         // 1: relaymesh.RelayPacket
	(*RoutingUpdate)(nil),       // 2: relaymesh.RoutingUpdate
	(*NodeRouteEntry)(nil),      // 3: relaymesh.NodeRouteEntry
	(*PeerList)(nil),            // 4: relaymesh.PeerList
	(*Ack)(nil),                 // 5: relaymesh.Ack
	(*RouteRequest)(nil),        // 6: relaymesh.RouteRequest
	(*RouteResponse)(nil),       // 7: relaymesh.RouteResponse
	(*RouteTable)(nil),          // 8: relaymesh.RouteTable
	(*RouteTableEntry)(nil),     // 9: relaymesh.RouteTableEntry
	(*RouteInvalidation)(nil),   // 10: relaymesh.RouteInvalidation
	(*EgressRequest)(nil),       // 11: relaymesh.EgressRequest
	(*EgressResponse)(nil),      // 12: relaymesh.EgressResponse
	(*NetworkMetrics)(nil),      // 13: relaymesh.NetworkMetrics
	(*PeerMetrics)(nil),         // 14: relaymesh.PeerMetrics
	(*TelemetryReport)(nil),     // 15: relaymesh.TelemetryReport
	(*NetworkState)(nil),        // 16: relaymesh.NetworkState
	(*PeerState)(nil),           // 17: relaymesh.PeerState
	(*RouteRecommendation)(nil), // 18: relaymesh.RouteRecommendation
	(*InferenceRequest)(nil),    // 19: relaymesh.InferenceRequest
	(*InferenceResponse)(nil),   // 20: relaymesh.InferenceResponse
	(*TrainingFeedback)(nil),    // 21: relaymesh.TrainingFeedback
	(*ModelInfoRequest)(nil),    // 22: relaymesh.ModelInfoRequest
	(*ModelInfo)(nil),           // 23: relaymesh.ModelInfo
}
var file_relaymesh_proto_depIdxs = []int32{
	3,  // 0: relaymesh.RoutingUpdate.routes:type_name -> relaymesh.NodeRouteEntry
	0,  // 1: relaymesh.PeerList.peers:type_name -> relaymesh.PeerAdvertisement
	9,  // 2: relaymesh.RouteTable.routes:type_name -> relaymesh.RouteTableEntry
	13, // 3: relaymesh.TelemetryReport.metrics:type_name -> relaymesh.NetworkMetrics
	14, // 4: relaymesh.TelemetryReport.peer_metrics:type_name -> relaymesh.PeerMetrics
	17, // 5: relaymesh.NetworkState.peers:type_name -> relaymesh.PeerState
	16, // 6: relaymesh.InferenceRequest.state:type_name -> relaymesh.NetworkState
	18, // 7: relaymesh.InferenceResponse.recommendations:type_name -> relaymesh.RouteRecommendation
	6,  // 8: relaymesh.RoutingService.GetRoute:input_type -> relaymesh.RouteRequest
	6,  // 9: relaymesh.RoutingService.GetRouteTable:input_type -> relaymesh.RouteRequest
	9,  // 10: relaymesh.RoutingService.UpdateRoute:input_type -> relaymesh.RouteTableEntry
	19, // 11: relaymesh.AIService.GetRecommendation:input_type -> relaymesh.InferenceRequest
	21, // 12: relaymesh.AIService.ReportFeedback:input_type -> relaymesh.TrainingFeedback
	22, // 13: relaymesh.AIService.GetModelInfo:input_type -> relaymesh.ModelInfoRequest
	15, // 14: relaymesh.TelemetryService.ReportTelemetry:input_type -> relaymesh.TelemetryReport
	6,  // 15: relaymesh.TelemetryService.GetTelemetry:input_type -> relaymesh.RouteRequest
	7,  // 16: relaymesh.RoutingService.GetRoute:output_type -> relaymesh.RouteResponse
	8,  // 17: relaymesh.RoutingService.GetRouteTable:output_type -> relaymesh.RouteTable
	10, // 18: relaymesh.RoutingService.UpdateRoute:output_type -> relaymesh.RouteInvalidation
	20, // 19: relaymesh.AIService.GetRecommendation:output_type -> relaymesh.InferenceResponse
	5,  // 20: relaymesh.AIService.ReportFeedback:output_type -> relaymesh.Ack
	23, // 21: relaymesh.AIService.GetModelInfo:output_type -> relaymesh.ModelInfo
	5,  // 22: relaymesh.TelemetryService.ReportTelemetry:output_type -> relaymesh.Ack
	15, // 23: relaymesh.TelemetryService.GetTelemetry:output_type -> relaymesh.TelemetryReport
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_relaymesh_proto_init() }
func file_relaymesh_proto_init() {
	if File_relaymesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relaymesh_proto_rawDesc), len(file_relaymesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_relaymesh_proto_goTypes,
		DependencyIndexes: file_relaymesh_proto_depIdxs,
		MessageInfos:      file_relaymesh_proto_msgTypes,
	}.Build()
	File_relaymesh_proto = out.File
	file_relaymesh_proto_goTypes = nil
	file_relaymesh_proto_depIdxs = nil
}
