# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import relaymesh_pb2 as relaymesh__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relaymesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoute = channel.unary_unary(
                '/relaymesh.RoutingService/GetRoute',
                request_serializer=relaymesh__pb2.RouteRequest.SerializeToString,
                response_deserializer=relaymesh__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.GetRouteTable = channel.unary_unary(
                '/relaymesh.RoutingService/GetRouteTable',
                request_serializer=relaymesh__pb2.RouteRequest.SerializeToString,
                response_deserializer=relaymesh__pb2.RouteTable.FromString,
                _registered_method=True)
        self.UpdateRoute = channel.unary_unary(
                '/relaymesh.RoutingService/UpdateRoute',
                request_serializer=relaymesh__pb2.RouteTableEntry.SerializeToString,
                response_deserializer=relaymesh__pb2.RouteInvalidation.FromString,
                _registered_method=True)


class RoutingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRouteTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoute,
                    request_deserializer=relaymesh__pb2.RouteRequest.FromString,
                    response_serializer=relaymesh__pb2.RouteResponse.SerializeToString,
            ),
            'GetRouteTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouteTable,
                    request_deserializer=relaymesh__pb2.RouteRequest.FromString,
                    response_serializer=relaymesh__pb2.RouteTable.SerializeToString,
            ),
            'UpdateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoute,
                    request_deserializer=relaymesh__pb2.RouteTableEntry.FromString,
                    response_serializer=relaymesh__pb2.RouteInvalidation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relaymesh.RoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relaymesh.RoutingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.RoutingService/GetRoute',
            relaymesh__pb2.RouteRequest.SerializeToString,
            relaymesh__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRouteTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.RoutingService/GetRouteTable',
            relaymesh__pb2.RouteRequest.SerializeToString,
            relaymesh__pb2.RouteTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.RoutingService/UpdateRoute',
            relaymesh__pb2.RouteTableEntry.SerializeToString,
            relaymesh__pb2.RouteInvalidation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendation = channel.unary_unary(
                '/relaymesh.AIService/GetRecommendation',
                request_serializer=relaymesh__pb2.InferenceRequest.SerializeToString,
                response_deserializer=relaymesh__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.ReportFeedback = channel.unary_unary(
                '/relaymesh.AIService/ReportFeedback',
                request_serializer=relaymesh__pb2.TrainingFeedback.SerializeToString,
                response_deserializer=relaymesh__pb2.Ack.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/relaymesh.AIService/GetModelInfo',
                request_serializer=relaymesh__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=relaymesh__pb2.ModelInfo.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=relaymesh__pb2.InferenceRequest.FromString,
                    response_serializer=relaymesh__pb2.InferenceResponse.SerializeToString,
            ),
            'ReportFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFeedback,
                    request_deserializer=relaymesh__pb2.TrainingFeedback.FromString,
                    response_serializer=relaymesh__pb2.Ack.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=relaymesh__pb2.ModelInfoRequest.FromString,
                    response_serializer=relaymesh__pb2.ModelInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relaymesh.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relaymesh.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.AIService/GetRecommendation',
            relaymesh__pb2.InferenceRequest.SerializeToString,
            relaymesh__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.AIService/ReportFeedback',
            relaymesh__pb2.TrainingFeedback.SerializeToString,
            relaymesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.AIService/GetModelInfo',
            relaymesh__pb2.ModelInfoRequest.SerializeToString,
            relaymesh__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TelemetryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportTelemetry = channel.unary_unary(
                '/relaymesh.TelemetryService/ReportTelemetry',
                request_serializer=relaymesh__pb2.TelemetryReport.SerializeToString,
                response_deserializer=relaymesh__pb2.Ack.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/relaymesh.TelemetryService/GetTelemetry',
                request_serializer=relaymesh__pb2.RouteRequest.SerializeToString,
                response_deserializer=relaymesh__pb2.TelemetryReport.FromString,
                _registered_method=True)


class TelemetryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTelemetry,
                    request_deserializer=relaymesh__pb2.TelemetryReport.FromString,
                    response_serializer=relaymesh__pb2.Ack.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=relaymesh__pb2.RouteRequest.FromString,
                    response_serializer=relaymesh__pb2.TelemetryReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relaymesh.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relaymesh.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.TelemetryService/ReportTelemetry',
            relaymesh__pb2.TelemetryReport.SerializeToString,
            relaymesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relaymesh.TelemetryService/GetTelemetry',
            relaymesh__pb2.RouteRequest.SerializeToString,
            relaymesh__pb2.TelemetryReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
